MyShop.UI/Controllers/BasketController.cs
using System.Linq;
using System.Web.Mvc;
using MyShop.Core.Contracts;
using MyShop.Core.Models;

namespace MyShop.UI.Controllers
{
	public class BasketController : Controller
	{
		IBasketService basketService;
		IOrderService orderService;
		IRepository<Customer> customerRepo;

		public BasketController(IBasketService basketService, IOrderService orderService, IRepository<Customer> customerRepo) {
			this.basketService = basketService;
			this.orderService = orderService;
			this.customerRepo = customerRepo;
		}

		public ActionResult Index() => View(basketService.GetBasketItems(this.HttpContext));

		public ActionResult AddToBasket(string productId) {
			basketService.AddToBasket(this.HttpContext, productId);
			return RedirectToAction("Index");
		}

		public ActionResult RemoveFromBasket(string basketItemId) {
			basketService.RemoveFromBasket(this.HttpContext, basketItemId);
			return RedirectToAction("Index");
		}

		public PartialViewResult BasketSummary() => PartialView(basketService.GetBasketSummary(this.HttpContext));

		[Authorize]
		public ActionResult Checkout() {
			var cust = customerRepo.Collection().FirstOrDefault(r => r.Email == User.Identity.Name);
			if (cust != null) {
				var order = new Order {
					Email = cust.Email,
					City = cust.City,
					State = cust.State,
					Street = cust.Street,
					FirstName = cust.FirstName,
					SurName = cust.LastName,
				};
				return View(order);
			}

			return RedirectToAction("Error");
		}

		[HttpPost]
		[Authorize]
		public ActionResult Checkout(Order order) {
			var items = basketService.GetBasketItems(this.HttpContext);
			order.OrderStatus = "Order Created";
			order.Email = User.Identity.Name;

			//Process payment

			order.OrderStatus = "Payment Processed";
			orderService.CreateOrder(order, items);
			basketService.ClearBasket(this.HttpContext);
			return RedirectToAction("Thankyou", new { OrderId = order.Id });
		}

		public ActionResult Thankyou(string orderId) {
			ViewBag.OrderId = orderId;
			return View();
		}
	}
}

MyShop.UI/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MyShop.Core.Contracts;
using MyShop.Core.Extensions;
using MyShop.Core.Models;
using MyShop.Core.ViewModels;

namespace MyShop.UI.Controllers
{
	public class HomeController : Controller
	{
		IRepository<Product> context;
		IRepository<ProductCategory> categoryContext;

		public HomeController(IRepository<Product> productContext, IRepository<ProductCategory> productCategoryContext) {
			context = productContext;
			categoryContext = productCategoryContext;
		}

		public ActionResult Index(string category = "") {
			var products = new List<Product>();
			if (category.HasValue()) {
				products.AddRange(context.Collection().Where(r => r.Category == category).ToList());
			}
			else {
				products.AddRange(context.Collection().ToList());
			}
			var model = new ProductListViewModel {
				Products = products,
				Categories = categoryContext.Collection().ToList()
			};
			return View(model);
		}

		public ActionResult Details(string id) {
			var product = context.Find(id);
			if (product == null)
				return HttpNotFound();
			return View(product);
		}

		public ActionResult About() {
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact() {
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

MyShop.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyShop.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyShop.UI/Views/Home/Details.cshtml
@model MyShop.Core.Models.Product

@{
	ViewBag.Title = $"{Model.Name} Details";
}

<h2>@Html.DisplayFor(r => r.Name)</h2>

<div>
	<div class="col-md-2">
		<img class="img-responsive" src="~/Content/ProductImages/@Model.Image" />
	</div>
	<div class="col-md-10">
		<dl class="dl-horizontal">
			<dt>
				@Html.DisplayNameFor(model => model.Description)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Description)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Price)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Price)
			</dd>
			<dt></dt>
			<dd>
				<a href="@Url.Action("AddToBasket","Basket",new { productId = Model.Id })" class="btn btn-default">Add to Basket</a>
			</dd>
			<dt></dt>
			<dd>@Html.ActionLink("Back to List", "Index")</dd>
		</dl>
	</div>
</div>
<div class="col-md-12 clearfix"></div>

MyShop.UI/Views/Home/Index.cshtml
@model MyShop.Core.ViewModels.ProductListViewModel

@{
	ViewBag.Title = "Home Page";
}


<h1>Products</h1>

<div class="col-md-2">
	<h4>Filter by Category</h4>
	<div class="list-group">
		@Html.ActionLink("All", "Index", null, new { @class = Request["Category"] == null ? "list-group-item active" : "list-group-item" })
		@foreach (var cat in Model.Categories) {
			@Html.ActionLink(cat.CategoryName, "Index", new { category = cat.CategoryName }, new { @class = Request["Category"] == cat.CategoryName ? "list-group-item active" : "list-group-item" })
		}
	</div>
</div>
<div class="col-md-10">

</div>

@foreach (var item in Model.Products) {
	<div class="col-md-4" style="height:450px;padding:10px;margin:10px;border:solid thin whitesmoke">
		<div class="col-md-12">
			<img class="img" style="height:250px" src="~/Content/ProductImages/@item.Image" />
		</div>
		<div class="col-md-12">
			<strong>
				@Html.ActionLink(item.Name, "Details", new { id = item.Id })
			</strong>
		</div>
		<div class="col-md-12">
			<p>@item.Description</p>
		</div>
		<div class="col-md-12">
			<h4>@item.Price</h4>
		</div>
		<div class="col-md-12">
			<a href="@Url.Action("AddToBasket","Basket",new { productId = item.Id })" class="btn btn-default">Add to Basket</a>
		</div>
	</div>
}

<div class="col-md-12 clearfix"></div>